image: maven:3.5.4-jdk-10

pipelines:
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn -B test -P default # -B batch mode makes Maven less verbose
