name: Javadoc

on:
  push:
    branches:
      - master
jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven: [ '3.8.5' ]
        java: [ '21' ]
    steps:
      - name: Step - Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Step - Build and test with Maven
        run: mvn verify

      - name: Step - Create javadoc
        run: |
          mvn javadoc:javadoc
          mv target/site/javadoc/ /tmp/.
