name: Coverage

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven: [ '3.8.5' ]
        java: [ '21' ]
    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Generate coverage
        id: coverage
        run: |
          mvn compile
          mvn test
          mvn jacoco:report
          display=`sed -nE 's/^.*<td>Total<([^>]+>){4}([^<]*).*$/\2/p' target/site/jacoco/index.html`
          echo "display=$display" >> $GITHUB_OUTPUT    # with the "%"
          coverage=${display%"%"}
          echo "coverage=$coverage" >> $GITHUB_OUTPUT  # without "%", treated as a number